/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 02/04/2022 14:48:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     150000000
#define MX_HCLKFreq_Value                       75000000
#define MX_FCLKCortexFreq_Value                 75000000
#define MX_CortexFreq_Value                     75000000
#define MX_AHBFreq_Value                        75000000
#define MX_APB1Freq_Value                       75000000
#define MX_APB2Freq_Value                       75000000
#define MX_APB1TimFreq_Value                    75000000
#define MX_APB2TimFreq_Value                    75000000
#define MX_ADC12Freq_Value                      150000000
#define MX_LPUART1Freq_Value                    75000000
#define MX_I2C1Freq_Value                       75000000
#define MX_I2SFreq_Value                        150000000
#define MX_USART1Freq_Value                     75000000
#define MX_USART2Freq_Value                     75000000
#define MX_USART3Freq_Value                     75000000
#define MX_FDCANFreq_Value                      75000000
#define MX_LPTIM1Freq_Value                     75000000
#define MX_QSPIFreq_Value                       150000000
#define MX_SAI1Freq_Value                       150000000
#define MX_PWRFreq_Value                        150000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_CECFreq_Value                        4000000
#define MX_HRTIM1Freq_Value                     75000000
#define MX_MCO1PinFreq_Value                    16000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PC2 */
#define MX_ADC1_IN8_Pin                         PC2
#define MX_ADC1_IN8_GPIOx                       GPIOC
#define MX_ADC1_IN8_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN8_GPIO_Pin                    GPIO_PIN_2
#define MX_ADC1_IN8_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PC1 */
#define MX_ADC1_IN7_Pin                         PC1
#define MX_ADC1_IN7_GPIOx                       GPIOC
#define MX_ADC1_IN7_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN7_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC1_IN7_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PC0 */
#define MX_ADC1_IN6_Pin                         PC0
#define MX_ADC1_IN6_GPIOx                       GPIOC
#define MX_ADC1_IN6_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN6_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC1_IN6_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- ADC2       --------------------------------*/

#define MX_ADC2                                 1

/* GPIO Configuration */

/* Pin PC5 */
#define MX_ADC2_IN11_Pin                        PC5
#define MX_ADC2_IN11_GPIOx                      GPIOC
#define MX_ADC2_IN11_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADC2_IN11_GPIO_Pin                   GPIO_PIN_5
#define MX_ADC2_IN11_GPIO_Mode                  GPIO_MODE_ANALOG

/* Pin PC4 */
#define MX_ADC2_IN5_Pin                         PC4
#define MX_ADC2_IN5_GPIOx                       GPIOC
#define MX_ADC2_IN5_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC2_IN5_GPIO_Pin                    GPIO_PIN_4
#define MX_ADC2_IN5_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Channel6_IRQn */
#define MX_DMA1_Channel6_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel6_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel6_IRQn_Subriority        0

/* NVIC DMA1_Channel3_IRQn */
#define MX_DMA1_Channel3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel3_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel3_IRQn_Subriority        0

/* NVIC DMA1_Channel1_IRQn */
#define MX_DMA1_Channel1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel1_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel1_IRQn_Subriority        0

/* NVIC DMA1_Channel2_IRQn */
#define MX_DMA1_Channel2_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel2_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel2_IRQn_Subriority        0

/* NVIC DMA1_Channel5_IRQn */
#define MX_DMA1_Channel5_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel5_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel5_IRQn_Subriority        0

/* NVIC DMA1_Channel4_IRQn */
#define MX_DMA1_Channel4_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Channel4_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_DMA1_Channel4_IRQn_Subriority        0

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PD15 */
#define MX_FMC_D1_Pin                           PD15
#define MX_FMC_D1_GPIOx                         GPIOD
#define MX_FMC_D1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_D1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_Pin                           PD0
#define MX_FMC_D2_GPIOx                         GPIOD
#define MX_FMC_D2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_D2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_FMC_ALE_Pin                          PD12
#define MX_FMC_ALE_GPIOx                        GPIOD
#define MX_FMC_ALE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_ALE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_ALE_GPIO_Pin                     GPIO_PIN_12
#define MX_FMC_ALE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_Pin                           PD1
#define MX_FMC_D3_GPIOx                         GPIOD
#define MX_FMC_D3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_D3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD6 */
#define MX_FMC_NWAIT_Pin                        PD6
#define MX_FMC_NWAIT_GPIOx                      GPIOD
#define MX_FMC_NWAIT_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_NWAIT_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWAIT_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_NWAIT_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_NWAIT_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_Pin                           PE7
#define MX_FMC_D4_GPIOx                         GPIOE
#define MX_FMC_D4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_GPIO_Pin                      GPIO_PIN_7
#define MX_FMC_D4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_Pin                           PE8
#define MX_FMC_D5_GPIOx                         GPIOE
#define MX_FMC_D5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_GPIO_Pin                      GPIO_PIN_8
#define MX_FMC_D5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_Pin                           PE9
#define MX_FMC_D6_GPIOx                         GPIOE
#define MX_FMC_D6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_GPIO_Pin                      GPIO_PIN_9
#define MX_FMC_D6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_Pin                           PE10
#define MX_FMC_D7_GPIOx                         GPIOE
#define MX_FMC_D7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_GPIO_Pin                      GPIO_PIN_10
#define MX_FMC_D7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FMC_CLE_Pin                          PD11
#define MX_FMC_CLE_GPIOx                        GPIOD
#define MX_FMC_CLE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_CLE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_CLE_GPIO_Pin                     GPIO_PIN_11
#define MX_FMC_CLE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FMC_NWE_Pin                          PD5
#define MX_FMC_NWE_GPIOx                        GPIOD
#define MX_FMC_NWE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NWE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWE_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_NWE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NWE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FMC_NOE_Pin                          PD4
#define MX_FMC_NOE_GPIOx                        GPIOD
#define MX_FMC_NOE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NOE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NOE_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_NOE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NOE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_FMC_NCE_Pin                          PD7
#define MX_FMC_NCE_GPIOx                        GPIOD
#define MX_FMC_NCE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NCE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NCE_GPIO_Pin                     GPIO_PIN_7
#define MX_FMC_NCE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NCE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_Pin                           PD14
#define MX_FMC_D0_GPIOx                         GPIOD
#define MX_FMC_D0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_D0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D0_GPIO_Mode                     GPIO_MODE_AF_PP

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PA15 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Pin                         PA15
#define MX_I2C1_SCL_GPIOx                       GPIOA
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_15
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_FM7                    __NULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- QUADSPI1   --------------------------------*/

#define MX_QUADSPI1                             1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_QUADSPI1_CLK_GPIO_Speed              GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_CLK_Pin                     PF10
#define MX_QUADSPI1_CLK_GPIOx                   GPIOF
#define MX_QUADSPI1_CLK_GPIO_PuPd               GPIO_NOPULL
#define MX_QUADSPI1_CLK_GPIO_Pin                GPIO_PIN_10
#define MX_QUADSPI1_CLK_GPIO_AF                 GPIO_AF10_QUADSPI
#define MX_QUADSPI1_CLK_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE11 */
#define MX_QUADSPI1_BK1_NCS_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_NCS_Pin                 PE11
#define MX_QUADSPI1_BK1_NCS_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_NCS_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_NCS_GPIO_Pin            GPIO_PIN_11
#define MX_QUADSPI1_BK1_NCS_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_NCS_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_QUADSPI1_BK1_IO3_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO3_Pin                 PE15
#define MX_QUADSPI1_BK1_IO3_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO3_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO3_GPIO_Pin            GPIO_PIN_15
#define MX_QUADSPI1_BK1_IO3_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO3_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_QUADSPI1_BK1_IO2_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO2_Pin                 PE14
#define MX_QUADSPI1_BK1_IO2_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO2_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO2_GPIO_Pin            GPIO_PIN_14
#define MX_QUADSPI1_BK1_IO2_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO2_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_QUADSPI1_BK1_IO1_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO1_Pin                 PF9
#define MX_QUADSPI1_BK1_IO1_GPIOx               GPIOF
#define MX_QUADSPI1_BK1_IO1_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO1_GPIO_Pin            GPIO_PIN_9
#define MX_QUADSPI1_BK1_IO1_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO1_GPIO_Mode           GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_QUADSPI1_BK1_IO0_GPIO_Speed          GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI1_BK1_IO0_Pin                 PE12
#define MX_QUADSPI1_BK1_IO0_GPIOx               GPIOE
#define MX_QUADSPI1_BK1_IO0_GPIO_PuPd           GPIO_NOPULL
#define MX_QUADSPI1_BK1_IO0_GPIO_Pin            GPIO_PIN_12
#define MX_QUADSPI1_BK1_IO0_GPIO_AF             GPIO_AF10_QUADSPI
#define MX_QUADSPI1_BK1_IO0_GPIO_Mode           GPIO_MODE_AF_PP

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PB13 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_SPI2_SCK_Pin                         PB13
#define MX_SPI2_SCK_GPIOx                       GPIOB
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_SCLK                             SPI2_SCK
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_13
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB15 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MOSI_Pin                        PB15
#define MX_SPI2_MOSI_GPIOx                      GPIOB
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADC_DOUT                             SPI2_MOSI
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_15
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PA8 */
#define MX_S_TIM1_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH1_Pin                       PA8
#define MX_S_TIM1_CH1_GPIOx                     GPIOA
#define MX_S_TIM1_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_ADC_CLK                              S_TIM1_CH1
#define MX_S_TIM1_CH1_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM1_CH1_GPIO_AF                   GPIO_AF6_TIM1

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PC8 */
#define MX_S_TIM3_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH3_Pin                       PC8
#define MX_S_TIM3_CH3_GPIOx                     GPIOC
#define MX_S_TIM3_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH3_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM3_CH3_GPIO_AF                   GPIO_AF2_TIM3

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PA10 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/* DMA Configuration */

/* DMA USART1_TX */
#define MX_USART1_TX_DMA_Instance               DMA1_Channel2
#define MX_USART1_TX_DMA_RequestGeneratorInstance None
#define MX_USART1_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_TX_DMA_SyncRequestNumber      1
#define MX_USART1_TX_DMA_Request                DMA_REQUEST_USART1_TX
#define MX_USART1_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART1_TX_DMA_SignalID               NONE
#define MX_USART1_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_TX_DMA_IpInstance
#define MX_USART1_TX_DMA_RequestNumber          1
#define MX_USART1_TX_DMA_EventEnable            DISABLE
#define MX_USART1_TX_DMA_SyncEnable             DISABLE
#define MX_USART1_TX_DMA_DMA_Handle
#define MX_USART1_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_TX_DMA_SyncSignalID           NONE
#define MX_USART1_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART1_RX */
#define MX_USART1_RX_DMA_Instance               DMA1_Channel1
#define MX_USART1_RX_DMA_RequestGeneratorInstance None
#define MX_USART1_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART1_RX_DMA_SyncRequestNumber      1
#define MX_USART1_RX_DMA_Request                DMA_REQUEST_USART1_RX
#define MX_USART1_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART1_RX_DMA_SignalID               NONE
#define MX_USART1_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_RX_DMA_IpInstance
#define MX_USART1_RX_DMA_RequestNumber          1
#define MX_USART1_RX_DMA_EventEnable            DISABLE
#define MX_USART1_RX_DMA_SyncEnable             DISABLE
#define MX_USART1_RX_DMA_DMA_Handle
#define MX_USART1_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_RX_DMA_SyncSignalID           NONE
#define MX_USART1_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 0
#define MX_USART1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART1_IRQn_Subriority               0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC
#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2

/* Pin PA1 */
#define MX_USART2_DE_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_DE_Pin                        PA1
#define MX_USART2_DE_GPIOx                      GPIOA
#define MX_USART2_DE_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_DE_GPIO_Pin                   GPIO_PIN_1
#define MX_USART2_DE_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_DE_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2

/* DMA Configuration */

/* DMA USART2_TX */
#define MX_USART2_TX_DMA_Instance               DMA1_Channel4
#define MX_USART2_TX_DMA_RequestGeneratorInstance None
#define MX_USART2_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART2_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART2_TX_DMA_SyncRequestNumber      1
#define MX_USART2_TX_DMA_Request                DMA_REQUEST_USART2_TX
#define MX_USART2_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART2_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART2_TX_DMA_SignalID               NONE
#define MX_USART2_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_TX_DMA_IpInstance
#define MX_USART2_TX_DMA_RequestNumber          1
#define MX_USART2_TX_DMA_EventEnable            DISABLE
#define MX_USART2_TX_DMA_SyncEnable             DISABLE
#define MX_USART2_TX_DMA_DMA_Handle
#define MX_USART2_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART2_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART2_TX_DMA_SyncSignalID           NONE
#define MX_USART2_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART2_RX */
#define MX_USART2_RX_DMA_Instance               DMA1_Channel3
#define MX_USART2_RX_DMA_RequestGeneratorInstance None
#define MX_USART2_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART2_RX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART2_RX_DMA_SyncRequestNumber      1
#define MX_USART2_RX_DMA_Request                DMA_REQUEST_USART2_RX
#define MX_USART2_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART2_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART2_RX_DMA_SignalID               NONE
#define MX_USART2_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_RX_DMA_IpInstance
#define MX_USART2_RX_DMA_RequestNumber          1
#define MX_USART2_RX_DMA_EventEnable            DISABLE
#define MX_USART2_RX_DMA_SyncEnable             DISABLE
#define MX_USART2_RX_DMA_DMA_Handle
#define MX_USART2_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART2_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART2_RX_DMA_SyncSignalID           NONE
#define MX_USART2_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 0
#define MX_USART2_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB10 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Pin                        PB10
#define MX_USART3_TX_GPIOx                      GPIOB
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PB11 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Pin                        PB11
#define MX_USART3_RX_GPIOx                      GPIOB
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3

/* DMA Configuration */

/* DMA USART3_TX */
#define MX_USART3_TX_DMA_Instance               DMA1_Channel6
#define MX_USART3_TX_DMA_RequestGeneratorInstance None
#define MX_USART3_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART3_TX_DMA_SyncRequestNumber      1
#define MX_USART3_TX_DMA_Request                DMA_REQUEST_USART3_TX
#define MX_USART3_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART3_TX_DMA_SignalID               NONE
#define MX_USART3_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_TX_DMA_IpInstance
#define MX_USART3_TX_DMA_RequestNumber          1
#define MX_USART3_TX_DMA_EventEnable            DISABLE
#define MX_USART3_TX_DMA_SyncEnable             DISABLE
#define MX_USART3_TX_DMA_DMA_Handle
#define MX_USART3_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_TX_DMA_SyncSignalID           NONE
#define MX_USART3_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART3_RX */
#define MX_USART3_RX_DMA_Instance               DMA1_Channel5
#define MX_USART3_RX_DMA_RequestGeneratorInstance None
#define MX_USART3_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART3_RX_DMA_SyncRequestNumber      1
#define MX_USART3_RX_DMA_Request                DMA_REQUEST_USART3_RX
#define MX_USART3_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART3_RX_DMA_SignalID               NONE
#define MX_USART3_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_RX_DMA_IpInstance
#define MX_USART3_RX_DMA_RequestNumber          1
#define MX_USART3_RX_DMA_EventEnable            DISABLE
#define MX_USART3_RX_DMA_SyncEnable             DISABLE
#define MX_USART3_RX_DMA_DMA_Handle
#define MX_USART3_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_RX_DMA_SyncSignalID           NONE
#define MX_USART3_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART3_IRQn */
#define MX_USART3_IRQn_interruptPremptionPriority 0
#define MX_USART3_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART3_IRQn_Subriority               0

/*-------------------------------- USB        --------------------------------*/

#define MX_USB                                  1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_DM_Pin                           PA11

/* Pin PA12 */
#define MX_USB_DP_Pin                           PA12

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PE6 */
#define MX_PE6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE6_Pin                              PE6
#define MX_PE6_GPIOx                            GPIOE
#define MX_PE6_PinState                         GPIO_PIN_SET
#define MX_PE6_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_MODE1                            PE6
#define MX_PE6_GPIO_Pin                         GPIO_PIN_6
#define MX_PE6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB3 */
#define MX_PB3_Pin                              PB3
#define MX_PB3_GPIOx                            GPIOB
#define MX_PB3_GPIO_PuPd                        GPIO_NOPULL
#define MX_GR                                   PB3
#define MX_PB3_GPIO_Pin                         GPIO_PIN_3
#define MX_PB3_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PE5 */
#define MX_PE5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE5_Pin                              PE5
#define MX_PE5_GPIOx                            GPIOE
#define MX_PE5_PinState                         GPIO_PIN_SET
#define MX_PE5_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_MODE0                            PE5
#define MX_PE5_GPIO_Pin                         GPIO_PIN_5
#define MX_PE5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PULSE                                PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PB4 */
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_FLOW                                 PB4
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PD8 */
#define MX_PD8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD8_Pin                              PD8
#define MX_PD8_GPIOx                            GPIOD
#define MX_PD8_PinState                         GPIO_PIN_RESET
#define MX_PD8_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_SYNC                             PD8
#define MX_PD8_GPIO_Pin                         GPIO_PIN_8
#define MX_PD8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB9 */
#define MX_PB9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB9_Pin                              PB9
#define MX_PB9_GPIOx                            GPIOB
#define MX_PB9_PinState                         GPIO_PIN_RESET
#define MX_PB9_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_CLKDIV                           PB9
#define MX_PB9_GPIO_Pin                         GPIO_PIN_9
#define MX_PB9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB9_GPIO_FM9                         __NULL

/* Pin PG10-NRST */
#define MX_PG10_NRST_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_PG10_NRST_Pin                        PG10_NRST
#define MX_PG10_NRST_GPIOx                      GPIOG
#define MX_PG10_NRST_PinState                   GPIO_PIN_RESET
#define MX_PG10_NRST_GPIO_PuPd                  GPIO_NOPULL
#define MX_ARM_RESET                            PG10_NRST
#define MX_PG10_NRST_GPIO_Pin                   GPIO_PIN_10
#define MX_PG10_NRST_GPIO_ModeDefaultOutputPP   GPIO_MODE_OUTPUT_PP

/* Pin PE0 */
#define MX_PE0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE0_Pin                              PE0
#define MX_PE0_GPIOx                            GPIOE
#define MX_PE0_PinState                         GPIO_PIN_SET
#define MX_PE0_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_FORMAT0                          PE0
#define MX_PE0_GPIO_Pin                         GPIO_PIN_0
#define MX_PE0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE2 */
#define MX_PE2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE2_Pin                              PE2
#define MX_PE2_GPIOx                            GPIOE
#define MX_PE2_PinState                         GPIO_PIN_RESET
#define MX_PE2_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_FORMAT2                          PE2
#define MX_PE2_GPIO_Pin                         GPIO_PIN_2
#define MX_PE2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE1 */
#define MX_PE1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE1_Pin                              PE1
#define MX_PE1_GPIOx                            GPIOE
#define MX_PE1_PinState                         GPIO_PIN_SET
#define MX_PE1_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_FORMAT1                          PE1
#define MX_PE1_GPIO_Pin                         GPIO_PIN_1
#define MX_PE1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE4 */
#define MX_PE4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE4_Pin                              PE4
#define MX_PE4_GPIOx                            GPIOE
#define MX_PE4_PinState                         GPIO_PIN_RESET
#define MX_PE4_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_PWDN_1                           PE4
#define MX_PE4_GPIO_Pin                         GPIO_PIN_4
#define MX_PE4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD3 */
#define MX_PD3_GPIO_Speed                       GPIO_SPEED_FREQ_HIGH
#define MX_PD3_Pin                              PD3
#define MX_PD3_GPIOx                            GPIOD
#define MX_PD3_PinState                         GPIO_PIN_SET
#define MX_PD3_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED_G                                PD3
#define MX_PD3_GPIO_Pin                         GPIO_PIN_3
#define MX_PD3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE3 */
#define MX_PE3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_PinState                         GPIO_PIN_RESET
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_ADC_PWDN_0                           PE3
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3
#define MX_PE3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD2 */
#define MX_PD2_GPIO_Speed                       GPIO_SPEED_FREQ_HIGH
#define MX_PD2_Pin                              PD2
#define MX_PD2_GPIOx                            GPIOD
#define MX_PD2_PinState                         GPIO_PIN_SET
#define MX_PD2_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED_R                                PD2
#define MX_PD2_GPIO_Pin                         GPIO_PIN_2
#define MX_PD2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

